
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EGAL = 10;
  public static final int READ = 12;
  public static final int ELSE = 18;
  public static final int IDENT = 8;
  public static final int NEG = 15;
  public static final int PLUS = 2;
  public static final int OR = 16;
  public static final int FOIS = 4;
  public static final int IF = 17;
  public static final int WRITE = 13;
  public static final int PV = 9;
  public static final int MOINS = 3;
  public static final int TYPE = 7;
  public static final int ENTIER = 11;
  public static final int EOF = 0;
  public static final int VIRG = 14;
  public static final int error = 1;
  public static final int PG = 5;
  public static final int PD = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MOINS",
  "FOIS",
  "PG",
  "PD",
  "TYPE",
  "IDENT",
  "PV",
  "EGAL",
  "ENTIER",
  "READ",
  "WRITE",
  "VIRG",
  "NEG",
  "OR",
  "IF",
  "ELSE"
  };
}

